# For Normal

In [125]:
import pandas as pd
data=pd.read_csv('normal4.pcap.csv',low_memory=False)

In [126]:
IP_MAC_MAPPING=data[["S_MAC","SIP"]].drop_duplicates().sort_values(by="SIP")
IP_MAC_MAPPING

                  S_MAC        SIP
0     be:05:40:56:af:35   10.0.0.1
14    7a:30:c6:03:0f:db  10.0.0.10
1     8e:5f:d2:c9:03:c5  10.0.0.11
23    06:79:dd:3f:87:16  10.0.0.12
2     fa:57:8f:59:f4:bb  10.0.0.13
307   2e:29:60:92:9c:21  10.0.0.14
9683  ce:8a:f7:cc:bc:ba  10.0.0.15
40    2a:61:e1:68:04:45  10.0.0.16
312   f2:92:ec:65:b1:21  10.0.0.17
16    52:56:0b:5e:25:69  10.0.0.18
316   06:29:f9:52:5c:f4  10.0.0.19
28    e2:05:e4:4f:fd:94   10.0.0.2
6     d6:eb:d0:ef:5c:ec  10.0.0.20
41    92:2b:e4:8c:5d:15  10.0.0.21
330   b2:01:c5:7f:27:4b  10.0.0.22
20    9e:9a:e2:14:c7:62  10.0.0.23
3     d2:46:92:96:89:55   10.0.0.3
21    86:e0:de:9e:32:ca   10.0.0.4
30    c6:e0:92:6b:61:09   10.0.0.5
17    6e:49:36:21:e1:8e   10.0.0.6
104   f6:02:4a:2a:55:64   10.0.0.7
8     72:23:46:5a:88:0c   10.0.0.8
32    1a:d2:5e:86:d6:b1   10.0.0.9

In [127]:
IoT_MAC=[]
CD_MAC=[]
NU_MAC=[]

IoT_IP=[]
CD_IP=[]
NU_IP=[]

for i in range (1,11):
    IoT_IP.append(f'10.0.0.{i}')
print(IoT_IP)

for i in range (11,15):
    CD_IP.append(f'10.0.0.{i}')
print(CD_IP)

for i in range (15,23):
    NU_IP.append(f'10.0.0.{i}')
print(NU_IP)


for i in IP_MAC_MAPPING.values:
    if i[1] in IoT_IP:
        IoT_MAC.append(i[0])
    elif i[1] in CD_IP:
        CD_MAC.append(i[0])
    else:
        NU_MAC.append(i[0])

['10.0.0.1', '10.0.0.2', '10.0.0.3', '10.0.0.4', '10.0.0.5', '10.0.0.6', '10.0.0.7', '10.0.0.8', '10.0.0.9', '10.0.0.10']
['10.0.0.11', '10.0.0.12', '10.0.0.13', '10.0.0.14']
['10.0.0.15', '10.0.0.16', '10.0.0.17', '10.0.0.18', '10.0.0.19', '10.0.0.20', '10.0.0.21', '10.0.0.22']

In [128]:
device_type=[]
D_type=["IoT","CD","NU"]
for i in data["S_MAC"]:
    # print(i)
    if i in IoT_MAC:
        device_type.append(D_type[0])
    elif i in CD_MAC:
        device_type.append(D_type[1])
    else:
        device_type.append(D_type[2])

    # break

In [129]:
data['D_type']=device_type

In [130]:
data[["S_MAC","SIP","D_type"]].drop_duplicates().sort_values(by="SIP")

                  S_MAC        SIP D_type
0     be:05:40:56:af:35   10.0.0.1    IoT
14    7a:30:c6:03:0f:db  10.0.0.10    IoT
1     8e:5f:d2:c9:03:c5  10.0.0.11     CD
23    06:79:dd:3f:87:16  10.0.0.12     CD
2     fa:57:8f:59:f4:bb  10.0.0.13     CD
307   2e:29:60:92:9c:21  10.0.0.14     CD
9683  ce:8a:f7:cc:bc:ba  10.0.0.15     NU
40    2a:61:e1:68:04:45  10.0.0.16     NU
312   f2:92:ec:65:b1:21  10.0.0.17     NU
16    52:56:0b:5e:25:69  10.0.0.18     NU
316   06:29:f9:52:5c:f4  10.0.0.19     NU
28    e2:05:e4:4f:fd:94   10.0.0.2    IoT
6     d6:eb:d0:ef:5c:ec  10.0.0.20     NU
41    92:2b:e4:8c:5d:15  10.0.0.21     NU
330   b2:01:c5:7f:27:4b  10.0.0.22     NU
20    9e:9a:e2:14:c7:62  10.0.0.23     NU
3     d2:46:92:96:89:55   10.0.0.3    IoT
21    86:e0:de:9e:32:ca   10.0.0.4    IoT
30    c6:e0:92:6b:61:09   10.0.0.5    IoT
17    6e:49:36:21:e1:8e   10.0.0.6    IoT
104   f6:02:4a:2a:55:64   10.0.0.7    IoT
8     72:23:46:5a:88:0c   10.0.0.8    IoT
32    1a:d2:5e:86:d6:b1   10.0.0.9    IoT

In [131]:
data.columns[100:]

Index(['HTTP_SCUL:', 'HTTP_SCM', 'DNSQTL', 'DNS_QTUL', 'DNS_QTM', 'DNS_RCL',
       'DNS_RCUL', 'DNS_RCM', 'MQTT_MTL', 'MQTT_MTUL', 'MQTT_MTM', 'RTSP_ML',
       'RTSP_MUL', 'RTSP_MM', 'RTSP_OptionC', 'RTSP_SETUPC', 'RTSP_DESCC',
       'RTSP_SPC', 'RTSP_RecordC', 'RTSP_TeardownC', 'RTSP_RedirectC',
       'RTSP_PlayC', 'RTSP_PauseC', 'label', 'type', 'D_type'],
      dtype='object')

In [132]:
data.to_csv("labeled_data/normal4.csv")

# Bonesi HTTP Flood

In [54]:
import pandas as pd
data=pd.read_csv('Bhttp_flood.pcap.csv',low_memory=False)

In [55]:
data[["D_MAC","DIP"]].drop_duplicates().sort_values(by="DIP")

                  D_MAC        DIP
1     72:67:7a:d9:e2:fd  10.0.0.12
3     66:7c:96:3f:9d:9e  10.0.0.13
8899  c6:5c:53:b0:57:07  10.0.0.14
0     4e:d2:91:47:fd:1d  10.0.0.18

In [56]:
data[data["D_MAC"] == "4e:d2:91:47:fd:1d"]

,S_MAC,D_MAC,FPT,LPT,FD,FAMin,FAMean,FAMax,FAStd,FIMean,...,RTSP_SETUPC,RTSP_DESCC,RTSP_SPC,RTSP_RecordC,RTSP_TeardownC,RTSP_RedirectC,RTSP_PlayC,RTSP_PauseC,label,type
0,c2:1b:0a:42:59:50,4e:d2:91:47:fd:1d,1.741170e+09,1.741170e+09,0.979422,0.979422,0.979422,0.979422,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
2831,c2:1b:0a:42:59:50,4e:d2:91:47:fd:1d,1.741170e+09,1.741170e+09,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
20626,c2:1b:0a:42:59:50,4e:d2:91:47:fd:1d,1.741170e+09,1.741170e+09,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap

In [57]:
data=data[data["D_MAC"] != "4e:d2:91:47:fd:1d"]

In [58]:
data[["D_MAC","DIP"]].drop_duplicates().sort_values(by="DIP")

                  D_MAC        DIP
1     72:67:7a:d9:e2:fd  10.0.0.12
3     66:7c:96:3f:9d:9e  10.0.0.13
8899  c6:5c:53:b0:57:07  10.0.0.14

In [59]:
data[data["D_MAC"] == "c6:5c:53:b0:57:07"]

,S_MAC,D_MAC,FPT,LPT,FD,FAMin,FAMean,FAMax,FAStd,FIMean,...,RTSP_SETUPC,RTSP_DESCC,RTSP_SPC,RTSP_RecordC,RTSP_TeardownC,RTSP_RedirectC,RTSP_PlayC,RTSP_PauseC,label,type
8899,66:7c:96:3f:9d:9e,c6:5c:53:b0:57:07,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
8961,66:7c:96:3f:9d:9e,c6:5c:53:b0:57:07,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
9035,66:7c:96:3f:9d:9e,c6:5c:53:b0:57:07,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
9114,66:7c:96:3f:9d:9e,c6:5c:53:b0:57:07,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
9221,66:7c:96:3f:9d:9e,c6:5c:53:b0:57:07,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3393073,66:7c:96:3f:9d:9e,c6:5c:53:b0:57:07,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
3393151,72:67:7a:d9:e2:fd,c6:5c:53:b0:57:07,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
3393196,66:7c:96:3f:9d:9e,c6:5c:53:b0:57:07,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
3393231,72:67:7a:d9:e2:fd,c6:5c:53:b0:57:07,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
3393293,66:7c:96:3f:9d:9e,c6:5c:53:b0:57:07,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap

In [60]:
data=data[data["D_MAC"] != 'c6:5c:53:b0:57:07']

In [61]:
data[data["S_MAC"] == 'c6:5c:53:b0:57:07']

,S_MAC,D_MAC,FPT,LPT,FD,FAMin,FAMean,FAMax,FAStd,FIMean,...,RTSP_SETUPC,RTSP_DESCC,RTSP_SPC,RTSP_RecordC,RTSP_TeardownC,RTSP_RedirectC,RTSP_PlayC,RTSP_PauseC,label,type
8900,c6:5c:53:b0:57:07,66:7c:96:3f:9d:9e,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
8963,c6:5c:53:b0:57:07,66:7c:96:3f:9d:9e,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
9043,c6:5c:53:b0:57:07,66:7c:96:3f:9d:9e,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
9115,c6:5c:53:b0:57:07,66:7c:96:3f:9d:9e,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
9330,c6:5c:53:b0:57:07,66:7c:96:3f:9d:9e,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3393075,c6:5c:53:b0:57:07,66:7c:96:3f:9d:9e,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
3393200,c6:5c:53:b0:57:07,72:67:7a:d9:e2:fd,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
3393201,c6:5c:53:b0:57:07,66:7c:96:3f:9d:9e,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
3393294,c6:5c:53:b0:57:07,72:67:7a:d9:e2:fd,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
3393295,c6:5c:53:b0:57:07,66:7c:96:3f:9d:9e,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap

In [62]:
data=data[data["S_MAC"] != 'c6:5c:53:b0:57:07']

In [63]:
data

,S_MAC,D_MAC,FPT,LPT,FD,FAMin,FAMean,FAMax,FAStd,FIMean,...,RTSP_SETUPC,RTSP_DESCC,RTSP_SPC,RTSP_RecordC,RTSP_TeardownC,RTSP_RedirectC,RTSP_PlayC,RTSP_PauseC,label,type
1,c2:1b:0a:42:59:50,72:67:7a:d9:e2:fd,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
2,c2:1b:0a:42:59:50,72:67:7a:d9:e2:fd,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
3,92:ae:50:01:10:33,66:7c:96:3f:9d:9e,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
4,c2:1b:0a:42:59:50,72:67:7a:d9:e2:fd,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
5,c2:1b:0a:42:59:50,72:67:7a:d9:e2:fd,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3393317,c2:1b:0a:42:59:50,72:67:7a:d9:e2:fd,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
3393318,c2:1b:0a:42:59:50,72:67:7a:d9:e2:fd,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
3393319,92:ae:50:01:10:33,66:7c:96:3f:9d:9e,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
3393320,c2:1b:0a:42:59:50,72:67:7a:d9:e2:fd,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap
3393321,c2:1b:0a:42:59:50,72:67:7a:d9:e2:fd,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,attack,Bhttp_flood.pcap

In [69]:
data["S_MAC"].unique()

array(['c2:1b:0a:42:59:50', '92:ae:50:01:10:33', '0e:3f:d9:e6:6b:75'],
      dtype=object)

In [83]:
data.query("SIP == '10.0.0.9' & DIP == '10.0.0.12' & DPort == 8808")["S_MAC"].unique()

array(['0e:3f:d9:e6:6b:75'], dtype=object)

In [84]:
data["D_MAC"].unique()

array(['72:67:7a:d9:e2:fd', '66:7c:96:3f:9d:9e'], dtype=object)

In [66]:
data[["D_MAC","DIP"]].drop_duplicates().sort_values(by="DIP")

               D_MAC        DIP
1  72:67:7a:d9:e2:fd  10.0.0.12
3  66:7c:96:3f:9d:9e  10.0.0.13

In [86]:
D_type=[]
for i in data["S_MAC"]:
    if i == '0e:3f:d9:e6:6b:75':
        D_type.append("IoT")
    elif i == 'c2:1b:0a:42:59:50' or '92:ae:50:01:10:33':
         D_type.append("NU")
    else:
        D_type.append("null")

In [88]:
data['D_type']=D_type

In [89]:
data.columns[100:]

Index(['HTTP_SCUL:', 'HTTP_SCM', 'DNSQTL', 'DNS_QTUL', 'DNS_QTM', 'DNS_RCL',
       'DNS_RCUL', 'DNS_RCM', 'MQTT_MTL', 'MQTT_MTUL', 'MQTT_MTM', 'RTSP_ML',
       'RTSP_MUL', 'RTSP_MM', 'RTSP_OptionC', 'RTSP_SETUPC', 'RTSP_DESCC',
       'RTSP_SPC', 'RTSP_RecordC', 'RTSP_TeardownC', 'RTSP_RedirectC',
       'RTSP_PlayC', 'RTSP_PauseC', 'label', 'type', 'D_type'],
      dtype='object')

In [90]:
data.to_csv("labeled_data/Bhttp_flood.csv")

# Bonesi ICMP Flood

In [91]:

import pandas as pd
data=pd.read_csv('Bicmp_flood.pcap.csv',low_memory=False)
data[["D_MAC","DIP"]].drop_duplicates().sort_values(by="DIP")

                  D_MAC        DIP
0     d2:84:86:c4:4d:e3  10.0.0.12
49    76:19:4c:e0:28:a5  10.0.0.13
3283  2e:7a:a1:82:bd:45  10.0.0.14

In [94]:
data=data[data["D_MAC"] != '2e:7a:a1:82:bd:45']

In [95]:
data[["D_MAC","DIP"]].drop_duplicates().sort_values(by="DIP")

                D_MAC        DIP
0   d2:84:86:c4:4d:e3  10.0.0.12
49  76:19:4c:e0:28:a5  10.0.0.13

In [97]:
data["S_MAC"].unique()

array(['46:82:86:c7:b1:72', 'ca:8f:ab:a3:01:61', '7a:96:16:fd:3d:50'],
      dtype=object)

In [103]:
data[["S_MAC","DIP"]].drop_duplicates().sort_values(by="DIP")

                 S_MAC        DIP
0    46:82:86:c7:b1:72  10.0.0.12
588  7a:96:16:fd:3d:50  10.0.0.12
49   ca:8f:ab:a3:01:61  10.0.0.13

In [ ]:
data.query("S_MAC == '7a:96:16:fd:3d:50' & DIP == '10.0.0.12' & SIP == '10.0.0.9'").shape[0],data.query("S_MAC == '46:82:86:c7:b1:72' & DIP == '10.0.0.12' & SIP == '10.0.0.9'").shape[0]
#                      10.0.0.23                                                                                             10.0.0.9

(96, 101)

In [108]:
data.query("S_MAC == '7a:96:16:fd:3d:50' & DIP == '10.0.0.12' & SIP == '10.0.0.23'").shape[0],data.query("S_MAC == '46:82:86:c7:b1:72' & DIP == '10.0.0.12' & SIP == '10.0.0.23'").shape[0]

(96, 101)

In [109]:
D_type=[]
for i in data["S_MAC"]:
    if i == '46:82:86:c7:b1:72':
        D_type.append("IoT")
    elif i == '7a:96:16:fd:3d:50' or 'ca:8f:ab:a3:01:61':
         D_type.append("NU")
    else:
        D_type.append("null")

In [110]:
data['D_type']=D_type

In [111]:
data.columns[100:]

Index(['HTTP_SCUL:', 'HTTP_SCM', 'DNSQTL', 'DNS_QTUL', 'DNS_QTM', 'DNS_RCL',
       'DNS_RCUL', 'DNS_RCM', 'MQTT_MTL', 'MQTT_MTUL', 'MQTT_MTM', 'RTSP_ML',
       'RTSP_MUL', 'RTSP_MM', 'RTSP_OptionC', 'RTSP_SETUPC', 'RTSP_DESCC',
       'RTSP_SPC', 'RTSP_RecordC', 'RTSP_TeardownC', 'RTSP_RedirectC',
       'RTSP_PlayC', 'RTSP_PauseC', 'label', 'type', 'D_type'],
      dtype='object')

In [112]:
data['D_type'].unique()

array(['IoT', 'NU'], dtype=object)

In [113]:
data.to_csv("labeled_data/Bicmp_flood.csv")

# Bonesi mqtt udp flood

In [ ]:

import pandas as pd
data=pd.read_csv('Bmqtt_udp_flood.pcap.csv',low_memory=False)
data[["D_MAC","DIP"]].drop_duplicates().sort_values(by="DIP")

                     D_MAC        DIP
0        2a:3d:d0:f5:3e:1d  10.0.0.11
552522   3a:2a:27:6f:ca:ae  10.0.0.14
3345677  ae:15:e8:ff:03:43  10.0.0.18

In [118]:
data=data[data['D_MAC']!='ae:15:e8:ff:03:43']
data=data[data['D_MAC']!='3a:2a:27:6f:ca:ae']
data[["D_MAC","DIP"]].drop_duplicates().sort_values(by="DIP")

               D_MAC        DIP
0  2a:3d:d0:f5:3e:1d  10.0.0.11

In [119]:
data["S_MAC"].unique()

array(['fa:74:83:ee:9e:7c', '8e:54:a3:6f:9c:c2', '52:cc:c4:49:2f:5c',
       '7e:d9:f2:d2:1d:ff', '26:22:86:56:9e:59', 'f2:de:ab:e4:79:c5',
       'fe:29:02:07:42:26'], dtype=object)

In [120]:
data['D_type']='IoT'

In [122]:
data['D_type'].unique()

array(['IoT'], dtype=object)

In [123]:
data.to_csv("labeled_data/Bmqtt_udp_flood.csv")

# Bonesi TCP flood

In [124]:

import pandas as pd
data=pd.read_csv('Btcp_flood.pcap.csv',low_memory=False)
data[["D_MAC","DIP"]].drop_duplicates().sort_values(by="DIP")

                     D_MAC        DIP
1588     8e:ff:57:30:6f:f1  10.0.0.14
0        7a:e3:0d:64:1b:7a  10.0.0.16
1449410  ae:89:a0:d0:27:57  10.0.0.18

In [127]:
data=data[data["D_MAC"]!='8e:ff:57:30:6f:f1']
data=data[data["D_MAC"]!='ae:89:a0:d0:27:57']

In [133]:
data=data[data["S_MAC"]!='8e:ff:57:30:6f:f1']

In [137]:
data[["S_MAC","DIP"]].drop_duplicates().sort_values(by="S_MAC")

                  S_MAC        DIP
0     1e:5a:47:93:77:3d  10.0.0.16
1113  c6:da:6a:b3:86:fc  10.0.0.16
1660  da:3c:d0:c2:0c:21  10.0.0.16

In [136]:
data['S_MAC'].unique()

array(['1e:5a:47:93:77:3d', 'c6:da:6a:b3:86:fc', 'da:3c:d0:c2:0c:21'],
      dtype=object)

In [145]:
D_type=[]
for i in data["S_MAC"]:
    if i == '1e:5a:47:93:77:3d':
        D_type.append("IoT")
    elif i == 'c6:da:6a:b3:86:fc' or 'da:3c:d0:c2:0c:21':
         D_type.append("NU")
    else:
        D_type.append("null")

In [146]:
data['D_type']=D_type

In [147]:
data['D_type'].unique()

array(['IoT', 'NU'], dtype=object)

In [148]:
data.to_csv("labeled_data/Btcp_flood.csv")

# Bonesi UDP flood

In [157]:
import pandas as pd
data=pd.read_csv('Budp_flood.pcap.csv',low_memory=False)
data[["D_MAC","DIP"]].drop_duplicates().sort_values(by="D_MAC")

                    D_MAC        DIP
772783  3a:c8:c6:c3:60:50  10.0.0.18
103099  9e:2a:20:7b:5e:34  10.0.0.14
0       9e:68:c7:15:ff:56   10.0.0.3

In [ ]:
data=data[data['D_MAC']!='9e:2a:20:7b:5e:34']
data=data[data['D_MAC']!='3a:c8:c6:c3:60:50']
data

In [159]:
data['S_MAC'].unique()

array(['d6:39:78:19:66:63', '2a:6d:30:53:12:a1'], dtype=object)

In [160]:
data['D_type']='NU'

In [163]:
data.to_csv("labeled_data/Budp_flood.csv")

# Hping3 ICMP Flood

In [164]:
import pandas as pd
data=pd.read_csv('Hicmp_flood.pcap.csv',low_memory=False)
data[["D_MAC","DIP"]].drop_duplicates().sort_values(by="D_MAC")

                  D_MAC       DIP
0     6e:b7:66:25:a7:5e  10.0.0.1
2044  d6:a5:b5:2d:62:5b  10.0.0.6

In [165]:
data['S_MAC'].unique()

array(['ba:88:77:4b:7a:8c', 'b6:f3:8b:98:98:da'], dtype=object)

In [166]:
data['D_type']='NU'

In [167]:
data['D_type'].unique()

array(['NU'], dtype=object)

In [168]:
data.to_csv("labeled_data/Hicmp_flood.csv")

# Hping3 mqtt tcp syn flood

In [169]:
import pandas as pd
data=pd.read_csv('Hmqtt_TcpSyn_flood.pcap.csv',low_memory=False)
data[["D_MAC","DIP"]].drop_duplicates().sort_values(by="D_MAC")

                     D_MAC        DIP
0        62:96:19:42:3d:5f  10.0.0.11
2174245  e6:e1:07:e1:6b:37  10.0.0.18

In [172]:
data=data[data['D_MAC']!='e6:e1:07:e1:6b:37']

In [174]:
data['D_MAC'].unique()

array(['62:96:19:42:3d:5f'], dtype=object)

In [173]:
data['S_MAC'].unique()

array(['b2:ab:f5:f4:6a:ec', '5a:95:64:8f:b3:b6', '1a:b5:24:b1:05:47',
       'ea:3b:5b:86:87:15', 'ea:d0:b7:53:a8:66', 'e6:77:15:b2:16:d0',
       '12:44:cd:3f:90:39'], dtype=object)

In [175]:
data['D_type']='IoT'

In [176]:
data['D_type'].unique()

array(['IoT'], dtype=object)

In [177]:
data.to_csv("labeled_data/Hmqtt_TcpSyn_flood.csv")

# Hping3 TCP Flood

In [184]:
import pandas as pd
data=pd.read_csv('Htcp_flood.pcap.csv',low_memory=False)
data[["D_MAC","DIP"]].drop_duplicates().sort_values(by="D_MAC")

                  D_MAC        DIP
5545  4a:f7:87:ca:f0:9f  10.0.0.14
448   66:24:4d:0d:e1:00  10.0.0.13
0     8a:87:7d:38:4d:d2  10.0.0.12
5549  ba:25:a6:c3:31:3e  10.0.0.18

In [185]:
data=data[data['D_MAC']!='4a:f7:87:ca:f0:9f']
data=data[data['D_MAC']!='ba:25:a6:c3:31:3e']

In [186]:
data[["D_MAC","DIP"]].drop_duplicates().sort_values(by="D_MAC")

                 D_MAC        DIP
448  66:24:4d:0d:e1:00  10.0.0.13
0    8a:87:7d:38:4d:d2  10.0.0.12

In [187]:
data['S_MAC'].unique()

array(['da:b8:41:50:18:6e', '3a:0e:4c:1c:c8:2f'], dtype=object)

In [188]:
data['D_type']='NU'

In [190]:
data.to_csv("labeled_data/Htcp_flood.csv")

# Hping3 UDP flood

In [191]:
import pandas as pd
data=pd.read_csv('Hudp_flood.pcap.csv',low_memory=False)
data[["D_MAC","DIP"]].drop_duplicates().sort_values(by="D_MAC")

                    D_MAC        DIP
419329  3a:4d:45:c0:73:9e  10.0.0.18
529279  a2:c0:e9:83:3e:3d  10.0.0.14
0       d2:c4:88:e3:23:70  10.0.0.12
1595    ea:ff:a2:e9:10:ad  10.0.0.11

In [194]:
data=data[data['D_MAC']!='a2:c0:e9:83:3e:3d']
data=data[data['D_MAC']!='3a:4d:45:c0:73:9e']

In [195]:
data[["D_MAC","DIP"]].drop_duplicates().sort_values(by="D_MAC")

                  D_MAC        DIP
0     d2:c4:88:e3:23:70  10.0.0.12
1595  ea:ff:a2:e9:10:ad  10.0.0.11

In [198]:
data=data[data['S_MAC']!='a2:c0:e9:83:3e:3d']

In [199]:
data['D_type']='NU'

In [201]:
data.to_csv("labeled_data/Hudp_flood.csv")

# MQTT Publish Flood

In [202]:
import pandas as pd
data=pd.read_csv('mqtt_publish_flood.pcap.csv',low_memory=False)
data[["D_MAC","DIP"]].drop_duplicates().sort_values(by="D_MAC")

                   D_MAC        DIP
0      be:0b:13:4c:1c:cb  10.0.0.11
19274  ea:b8:b2:4f:7a:5a  10.0.0.18

In [205]:
data=data[data['D_MAC']!='ea:b8:b2:4f:7a:5a']

In [206]:
data['S_MAC'].unique()

array(['ce:8c:ea:67:4c:c9', '86:b7:95:36:68:26', '96:41:9b:85:76:b5',
       'fe:35:1d:3d:b8:d8', 'da:18:48:c7:64:48', '8e:89:cf:b4:0e:4a',
       'be:ac:f4:16:5d:7e'], dtype=object)

In [207]:
data['D_type']='IoT'

In [208]:
data.to_csv("labeled_data/mqtt_publish_flood.csv")

# Next

In [209]:
import pandas as pd
data=pd.read_csv('mqtt_publish_flood1.pcap.csv',low_memory=False)
data[["D_MAC","DIP"]].drop_duplicates().sort_values(by="D_MAC")

                   D_MAC        DIP
0      3a:d4:c9:f6:b2:7e  10.0.0.11
33545  9a:ac:f5:b8:32:72  10.0.0.14
33547  b6:fb:2d:b0:b3:31  10.0.0.18

In [212]:
data=data[data['D_MAC']!='b6:fb:2d:b0:b3:31']
data=data[data['D_MAC']!='9a:ac:f5:b8:32:72']

In [213]:
data[["D_MAC","DIP"]].drop_duplicates().sort_values(by="D_MAC")

               D_MAC        DIP
0  3a:d4:c9:f6:b2:7e  10.0.0.11

In [214]:
data['S_MAC'].unique()

array(['a6:82:13:11:40:dc', 'f2:94:c1:f2:86:9c', '02:3e:c2:98:b6:13',
       '96:ef:9a:ab:c8:79', 'ca:a0:6b:1e:81:50', '1e:66:8b:37:9b:d5',
       '36:f0:f2:07:c6:77'], dtype=object)

In [215]:
data['D_type']='IoT'
data.to_csv("labeled_data/mqtt_publish_flood1.csv")

# Datasets in One

In [1]:
import pandas as pd
import os
from glob import glob

# Define the directory containing the CSV files
directory = "labeled_data/"  # Change to your actual directory

# Get all CSV files in the directory
csv_files = glob(os.path.join(directory, "*.csv"))

# Load and combine all CSV files
df_list = [pd.read_csv(file) for file in csv_files]
combined_df = pd.concat(df_list, ignore_index=True)

# Save the combined DataFrame to a new CSV file
# output_file = "RAW_SDN_IoT_Dataset.csv"
# combined_df.to_csv(output_file, index=False)

# print(f"[INFO] Merged {len(csv_files)} CSV files into {output_file}")

C:\Users\DELL\AppData\Local\Temp\ipykernel_16372\2972119657.py:12: DtypeWarning: Columns (90) have mixed types. Specify dtype option on import or set low_memory=False.
  df_list = [pd.read_csv(file) for file in csv_files]
C:\Users\DELL\AppData\Local\Temp\ipykernel_16372\2972119657.py:12: DtypeWarning: Columns (90) have mixed types. Specify dtype option on import or set low_memory=False.
  df_list = [pd.read_csv(file) for file in csv_files]

In [2]:
col2remv=[]
for i in combined_df:
    if combined_df[i].isna().sum()>0:
        col2remv.append(i)

In [3]:
combined_df.dropna(axis=1,inplace=True)

In [5]:
combined_df.drop(['Unnamed: 0'],axis=1,inplace=True)

In [6]:
combined_df.columns

Index(['S_MAC', 'D_MAC', 'FPT', 'LPT', 'FD', 'FAMin', 'FAMean', 'FAMax',
       'FAStd', 'FIMean',
       ...
       'DNS_QTUL', 'DNS_RCL', 'DNS_RCUL', 'MQTT_MTL', 'MQTT_MTUL', 'RTSP_ML',
       'RTSP_MUL', 'label', 'type', 'D_type'],
      dtype='object', length=101)

In [7]:
combined_df.to_csv('Step1.csv', index=False)

In [8]:
single_values_columns=[]
for i in combined_df:
    if len(combined_df[i].unique())<2:
        single_values_columns.append(i)

In [10]:
len(single_values_columns)

23

In [12]:
combined_df.drop(single_values_columns,axis=1,inplace=True)

In [13]:
combined_df

,S_MAC,D_MAC,FPT,LPT,FD,FAMin,FAMean,FAMax,FAStd,FIMean,...,TCPWS_Sum,TCPWS_Mean,TCPWS_Mode,HTTPRM_L,HTTPRM_UL,HTTP_SCL,HTTP_SCUL:,label,type,D_type
0,c2:1b:0a:42:59:50,72:67:7a:d9:e2:fd,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,4096,4096.0,4096,0,0,0,0,attack,Bhttp_flood.pcap,NU
1,c2:1b:0a:42:59:50,72:67:7a:d9:e2:fd,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,4096,4096.0,4096,0,0,0,0,attack,Bhttp_flood.pcap,NU
2,92:ae:50:01:10:33,66:7c:96:3f:9d:9e,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,4096,4096.0,4096,0,0,0,0,attack,Bhttp_flood.pcap,NU
3,c2:1b:0a:42:59:50,72:67:7a:d9:e2:fd,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,4096,4096.0,4096,0,0,0,0,attack,Bhttp_flood.pcap,NU
4,c2:1b:0a:42:59:50,72:67:7a:d9:e2:fd,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,4096,4096.0,4096,0,0,0,0,attack,Bhttp_flood.pcap,NU
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33356911,f2:92:ec:65:b1:21,06:29:f9:52:5c:f4,1.741095e+09,1.741095e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,83,83.0,83,0,0,0,0,normal,normal,NU
33356912,f2:92:ec:65:b1:21,06:29:f9:52:5c:f4,1.741095e+09,1.741095e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,85,85.0,85,0,0,0,0,normal,normal,NU
33356913,06:29:f9:52:5c:f4,f2:92:ec:65:b1:21,1.741095e+09,1.741095e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,85,85.0,85,0,0,0,0,normal,normal,NU
33356914,d2:46:92:96:89:55,8e:5f:d2:c9:03:c5,1.741095e+09,1.741095e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,83,83.0,83,0,0,0,0,normal,normal,IoT
33356915,8e:5f:d2:c9:03:c5,d2:46:92:96:89:55,1.741095e+09,1.741095e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,85,85.0,85,0,0,0,0,normal,normal,CD

In [14]:
combined_df.to_csv('Step2.csv', index=False)

In [1]:
import pandas as pd
combined_df=pd.read_csv('Step2.csv',low_memory=False)

In [4]:
combined_df['type'].value_counts()

type
Hudp_flood.pcap             5353295
hmqtt_TcpSyn_flood.pcap     4816624
Hicmp_flood.pcap            4572914
Htcp_flood.pcap             4426750
Btcp_flood.pcap             3901461
Bmqtt_udp_flood.pcap        3466258
Bhttp_flood.pcap            3272116
Budp_flood.pcap             3228636
mqtt_publish_flood1.pcap     174881
normal                        89973
mqtt_publish_flood.pcap       39406
Bicmp_flood.pcap              14602
Name: count, dtype: int64

In [5]:
combined_df.drop_duplicates()

,S_MAC,D_MAC,FPT,LPT,FD,FAMin,FAMean,FAMax,FAStd,FIMean,...,TCPWS_Sum,TCPWS_Mean,TCPWS_Mode,HTTPRM_L,HTTPRM_UL,HTTP_SCL,HTTP_SCUL:,label,type,D_type
0,c2:1b:0a:42:59:50,72:67:7a:d9:e2:fd,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,4096,4096.0,4096,0,0,0,0,attack,Bhttp_flood.pcap,NU
1,c2:1b:0a:42:59:50,72:67:7a:d9:e2:fd,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,4096,4096.0,4096,0,0,0,0,attack,Bhttp_flood.pcap,NU
2,92:ae:50:01:10:33,66:7c:96:3f:9d:9e,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,4096,4096.0,4096,0,0,0,0,attack,Bhttp_flood.pcap,NU
3,c2:1b:0a:42:59:50,72:67:7a:d9:e2:fd,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,4096,4096.0,4096,0,0,0,0,attack,Bhttp_flood.pcap,NU
4,c2:1b:0a:42:59:50,72:67:7a:d9:e2:fd,1.741170e+09,1.741170e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,4096,4096.0,4096,0,0,0,0,attack,Bhttp_flood.pcap,NU
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33356911,f2:92:ec:65:b1:21,06:29:f9:52:5c:f4,1.741095e+09,1.741095e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,83,83.0,83,0,0,0,0,normal,normal,NU
33356912,f2:92:ec:65:b1:21,06:29:f9:52:5c:f4,1.741095e+09,1.741095e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,85,85.0,85,0,0,0,0,normal,normal,NU
33356913,06:29:f9:52:5c:f4,f2:92:ec:65:b1:21,1.741095e+09,1.741095e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,85,85.0,85,0,0,0,0,normal,normal,NU
33356914,d2:46:92:96:89:55,8e:5f:d2:c9:03:c5,1.741095e+09,1.741095e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,83,83.0,83,0,0,0,0,normal,normal,IoT
33356915,8e:5f:d2:c9:03:c5,d2:46:92:96:89:55,1.741095e+09,1.741095e+09,0.0,0.0,0.0,0.0,0.0,0.0,...,85,85.0,85,0,0,0,0,normal,normal,CD

In [ ]:
import pandas as pd
import random


# Dataset statistics (class names and instance counts)
class_counts = {
    "Hudp_flood.pcap": 5353295,
    "hmqtt_TcpSyn_flood.pcap": 4816624,
    "Hicmp_flood.pcap": 4572914,
    "Htcp_flood.pcap": 4426750,
    "Btcp_flood.pcap": 3901461,
    "Bmqtt_udp_flood.pcap": 3466258,
    "Bhttp_flood.pcap": 3272116,
    "Budp_flood.pcap": 3228636,
    "mqtt_publish_flood1.pcap": 174881,
    "normal": 89973,  # Target count for balancing
    "mqtt_publish_flood.pcap": 39406,
    "Bicmp_flood.pcap": 14602,
}

# Load the dataset

# Separate the data by class
balanced_df = pd.DataFrame()  # To store balanced data

for class_name, count in class_counts.items():
    class_subset = combined_df[combined_df["type"] == class_name]  # Filter by class
    
    if len(class_subset) > class_counts["normal"]:  # If more than 89,973 instances
        class_subset = class_subset.sample(class_counts["normal"], random_state=42)  # Undersample
    elif len(class_subset) < class_counts["normal"]:  # If fewer, keep as is
        class_subset = class_subset  # No oversampling applied here
    
    balanced_df = pd.concat([balanced_df, class_subset])  # Merge to final dataset

# Save the balanced dataset
balanced_df.to_csv("balanced_dataset.csv", index=False)

print("[INFO] Dataset balanced successfully! New class distribution:")
print(balanced_df["type"].value_counts())

[INFO] Dataset balanced successfully! New class distribution:
type
Hudp_flood.pcap             89973
hmqtt_TcpSyn_flood.pcap     89973
Hicmp_flood.pcap            89973
Htcp_flood.pcap             89973
Btcp_flood.pcap             89973
Bmqtt_udp_flood.pcap        89973
Bhttp_flood.pcap            89973
Budp_flood.pcap             89973
mqtt_publish_flood1.pcap    89973
normal                      89973
mqtt_publish_flood.pcap     39406
Bicmp_flood.pcap            14602
Name: count, dtype: int64

In [2]:
89973*9+39406+14602+89973

953738

In [8]:
balanced_df

,S_MAC,D_MAC,FPT,LPT,FD,FAMin,FAMean,FAMax,FAStd,FIMean,...,TCPWS_Sum,TCPWS_Mean,TCPWS_Mode,HTTPRM_L,HTTPRM_UL,HTTP_SCL,HTTP_SCUL:,label,type,D_type
31833297,1a:bf:56:94:b7:a2,d2:c4:88:e3:23:70,1.741113e+09,1.741113e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,0.0,0,0,0,0,0,attack,Hudp_flood.pcap,NU
28029107,1a:bf:56:94:b7:a2,d2:c4:88:e3:23:70,1.741113e+09,1.741113e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,0.0,0,0,0,0,0,attack,Hudp_flood.pcap,NU
31805637,76:a8:e5:1f:24:37,ea:ff:a2:e9:10:ad,1.741113e+09,1.741113e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,0.0,0,0,0,0,0,attack,Hudp_flood.pcap,NU
28683495,1a:bf:56:94:b7:a2,d2:c4:88:e3:23:70,1.741113e+09,1.741113e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,0.0,0,0,0,0,0,attack,Hudp_flood.pcap,NU
31811803,1a:bf:56:94:b7:a2,d2:c4:88:e3:23:70,1.741113e+09,1.741113e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,0.0,0,0,0,0,0,attack,Hudp_flood.pcap,NU
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3286713,46:82:86:c7:b1:72,d2:84:86:c4:4d:e3,1.741181e+09,1.741181e+09,0.138632,0.004183,0.027726,0.049643,0.015071,0.004700,...,0,0.0,0,0,0,0,0,attack,Bicmp_flood.pcap,IoT
3286714,46:82:86:c7:b1:72,d2:84:86:c4:4d:e3,1.741181e+09,1.741181e+09,0.138729,0.004188,0.027746,0.046105,0.014090,0.004646,...,0,0.0,0,0,0,0,0,attack,Bicmp_flood.pcap,IoT
3286715,46:82:86:c7:b1:72,d2:84:86:c4:4d:e3,1.741181e+09,1.741181e+09,0.135916,0.001299,0.027183,0.046640,0.015249,0.005254,...,0,0.0,0,0,0,0,0,attack,Bicmp_flood.pcap,IoT
3286716,46:82:86:c7:b1:72,d2:84:86:c4:4d:e3,1.741181e+09,1.741181e+09,0.135923,0.001303,0.027185,0.042792,0.014575,0.005218,...,0,0.0,0,0,0,0,0,attack,Bicmp_flood.pcap,IoT
3286717,46:82:86:c7:b1:72,d2:84:86:c4:4d:e3,1.741181e+09,1.741181e+09,0.135933,0.001280,0.027187,0.040474,0.014504,0.005082,...,0,0.0,0,0,0,0,0,attack,Bicmp_flood.pcap,IoT

In [9]:
balanced_df=balanced_df.sample(frac=1, random_state=42).reset_index(drop=True)

In [12]:
balanced_df['D_type'].value_counts()

D_type
NU     536450
IoT    385281
CD      32007
Name: count, dtype: int64

In [13]:
balanced_df.to_csv("Final_balanced_dataset.csv", index=False)

# From Here

In [3]:
import pandas as pd
data=pd.read_csv('Final_balanced_dataset.csv',low_memory=False)

In [10]:
data['type'].value_counts()

type
Hudp_flood.pcap             89973
Hicmp_flood.pcap            89973
Htcp_flood.pcap             89973
Btcp_flood.pcap             89973
hmqtt_TcpSyn_flood.pcap     89973
normal                      89973
mqtt_publish_flood1.pcap    89973
Budp_flood.pcap             89973
Bhttp_flood.pcap            89973
Bmqtt_udp_flood.pcap        89973
Bicmp_flood.pcap            14602
Name: count, dtype: int64

In [ ]:
data['label'].value_counts()

label
attack    824359
normal     89973
Name: count, dtype: int64

In [12]:
data['D_type'].value_counts()

D_type
NU     536450
IoT    345875
CD      32007
Name: count, dtype: int64

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.linear_model import RidgeClassifier

In [23]:
for i in data.columns:
    print(i)

S_MAC
D_MAC
FPT
LPT
FD
FAMin
FAMean
FAMax
FAStd
FIMean
FIMin
FIMax
FIStd
DSCP_C
ECN_C
TPackets
TBytes
SBytes
DBytes
PLM
FI
FIAT
BIAT
ForwardPC
BackwardPC
FlowR
FlowStd
FlowV
FH_M
FAPS
BAPS
FBPP
FFD
Proto
SIP
DIP
SPort
DPort
SDuration
SPC
SBCount
BytesPS
PacketsPS
RTT
HL_Sum
HL_Mode
HL_mean
SYN_FC
FIN_FC
RST_FC
PSH_FC
TCP_HD
RCount
DACount
MPackets
FThroughput
BThroughput
FJitter
BJitter
FBurst
FEntropy
PIA_Var
PL
PEntropy
SIT
STT
FIPD_Var
BIPD_Var
TCPWS_Sum
TCPWS_Mean
TCPWS_Mode
HTTPRM_L
HTTPRM_UL
HTTP_SCL
HTTP_SCUL:
label
type
D_type

In [14]:
# ID_Features=['S_MAC',
# 'D_MAC',
# 'FPT',
# 'LPT',
# 'SIT',
# 'STT',
# 'SIP',
# 'DIP',
# 'SPort',
# 'DPort',
# 'label',
# 'type']

ID_Features=['S_MAC',
'D_MAC',
'FPT',
'LPT',
'SIT',
'STT',
'SIP',
'DIP',
'SPort',
'DPort',
'label',
'type',
'D_type']

In [15]:
Y=data[ID_Features]
X=data.drop(ID_Features,axis=1)

In [16]:
for i in X:
      if X[i].dtype == 'object':
            print(i)
# no categorical data type

In [17]:
Y

,S_MAC,D_MAC,FPT,LPT,SIT,STT,SIP,DIP,SPort,DPort,label,type,D_type
0,1a:bf:56:94:b7:a2,d2:c4:88:e3:23:70,1.741113e+09,1.741113e+09,1.741113e+09,1.741113e+09,98.149.70.196,10.0.0.12,6284,5001,attack,Hudp_flood.pcap,NU
1,ba:88:77:4b:7a:8c,6e:b7:66:25:a7:5e,1.741114e+09,1.741114e+09,1.741114e+09,1.741114e+09,71.78.142.90,10.0.0.1,0,0,attack,Hicmp_flood.pcap,NU
2,3a:0e:4c:1c:c8:2f,66:24:4d:0d:e1:00,1.741112e+09,1.741112e+09,1.741112e+09,1.741112e+09,228.104.161.230,10.0.0.13,29060,8008,attack,Htcp_flood.pcap,NU
3,da:3c:d0:c2:0c:21,7a:e3:0d:64:1b:7a,1.741169e+09,1.741169e+09,1.741169e+09,1.741169e+09,10.0.0.32,10.0.0.16,13213,12345,attack,Btcp_flood.pcap,NU
4,5a:95:64:8f:b3:b6,62:96:19:42:3d:5f,1.741118e+09,1.741118e+09,1.741118e+09,1.741118e+09,165.117.88.49,10.0.0.11,15807,1883,attack,hmqtt_TcpSyn_flood.pcap,IoT
...,...,...,...,...,...,...,...,...,...,...,...,...,...
953733,ba:88:77:4b:7a:8c,6e:b7:66:25:a7:5e,1.741114e+09,1.741114e+09,1.741114e+09,1.741114e+09,122.241.162.97,10.0.0.1,0,0,attack,Hicmp_flood.pcap,NU
953734,da:3c:d0:c2:0c:21,7a:e3:0d:64:1b:7a,1.741169e+09,1.741169e+09,1.741169e+09,1.741169e+09,10.0.0.5,10.0.0.16,14629,12345,attack,Btcp_flood.pcap,NU
953735,b2:ab:f5:f4:6a:ec,62:96:19:42:3d:5f,1.741118e+09,1.741118e+09,1.741118e+09,1.741118e+09,48.218.3.190,10.0.0.11,12072,1883,attack,hmqtt_TcpSyn_flood.pcap,IoT
953736,d6:39:78:19:66:63,9e:68:c7:15:ff:56,1.741167e+09,1.741167e+09,1.741167e+09,1.741167e+09,10.0.0.47,10.0.0.3,16754,53,attack,Budp_flood.pcap,NU
953737,ea:d0:b7:53:a8:66,62:96:19:42:3d:5f,1.741118e+09,1.741118e+09,1.741118e+09,1.741118e+09,12.212.21.72,10.0.0.11,33670,1883,attack,hmqtt_TcpSyn_flood.pcap,IoT

In [18]:
# func for missing values imputation, encoding, and normalization

def encod(data):
  n=data.shape[1]
  from sklearn import preprocessing
  label_encoder = preprocessing.LabelEncoder()
  for i in range(n):
      if data.iloc[:,i].dtype == 'object':

        data.iloc[:,i]= label_encoder.fit_transform(data.iloc[:,i])
        unique_classes = label_encoder.classes_
        print("Unique Classes:", unique_classes)
        print("Encoded Labels:", data.iloc[:,i])
  return data


def normalize_scale(X):
  m= X.values #returns a numpy array
  cols_name = X.columns
  scaler = preprocessing.MinMaxScaler()
  x_scaled = scaler.fit_transform(m)
  #scaler.transform(X) for scaling using the previous weights
  Scale_X = pd.DataFrame(x_scaled,columns = cols_name)
  return Scale_X

In [ ]:
X=encod(X)

In [20]:
Y

,S_MAC,D_MAC,FPT,LPT,SIT,STT,SIP,DIP,SPort,DPort,label,type,D_type
0,1a:bf:56:94:b7:a2,d2:c4:88:e3:23:70,1.741113e+09,1.741113e+09,1.741113e+09,1.741113e+09,98.149.70.196,10.0.0.12,6284,5001,attack,Hudp_flood.pcap,NU
1,ba:88:77:4b:7a:8c,6e:b7:66:25:a7:5e,1.741114e+09,1.741114e+09,1.741114e+09,1.741114e+09,71.78.142.90,10.0.0.1,0,0,attack,Hicmp_flood.pcap,NU
2,3a:0e:4c:1c:c8:2f,66:24:4d:0d:e1:00,1.741112e+09,1.741112e+09,1.741112e+09,1.741112e+09,228.104.161.230,10.0.0.13,29060,8008,attack,Htcp_flood.pcap,NU
3,da:3c:d0:c2:0c:21,7a:e3:0d:64:1b:7a,1.741169e+09,1.741169e+09,1.741169e+09,1.741169e+09,10.0.0.32,10.0.0.16,13213,12345,attack,Btcp_flood.pcap,NU
4,5a:95:64:8f:b3:b6,62:96:19:42:3d:5f,1.741118e+09,1.741118e+09,1.741118e+09,1.741118e+09,165.117.88.49,10.0.0.11,15807,1883,attack,hmqtt_TcpSyn_flood.pcap,IoT
...,...,...,...,...,...,...,...,...,...,...,...,...,...
953733,ba:88:77:4b:7a:8c,6e:b7:66:25:a7:5e,1.741114e+09,1.741114e+09,1.741114e+09,1.741114e+09,122.241.162.97,10.0.0.1,0,0,attack,Hicmp_flood.pcap,NU
953734,da:3c:d0:c2:0c:21,7a:e3:0d:64:1b:7a,1.741169e+09,1.741169e+09,1.741169e+09,1.741169e+09,10.0.0.5,10.0.0.16,14629,12345,attack,Btcp_flood.pcap,NU
953735,b2:ab:f5:f4:6a:ec,62:96:19:42:3d:5f,1.741118e+09,1.741118e+09,1.741118e+09,1.741118e+09,48.218.3.190,10.0.0.11,12072,1883,attack,hmqtt_TcpSyn_flood.pcap,IoT
953736,d6:39:78:19:66:63,9e:68:c7:15:ff:56,1.741167e+09,1.741167e+09,1.741167e+09,1.741167e+09,10.0.0.47,10.0.0.3,16754,53,attack,Budp_flood.pcap,NU
953737,ea:d0:b7:53:a8:66,62:96:19:42:3d:5f,1.741118e+09,1.741118e+09,1.741118e+09,1.741118e+09,12.212.21.72,10.0.0.11,33670,1883,attack,hmqtt_TcpSyn_flood.pcap,IoT

In [21]:
EY=encod(Y)

Unique Classes: ['02:3e:c2:98:b6:13' '02:47:6a:5a:03:6a' '02:74:55:c5:ea:d9'
 '06:1d:58:18:44:d2' '06:29:f9:52:5c:f4' '06:79:dd:3f:87:16'
 '0a:4d:2d:fb:69:52' '0a:73:ba:bb:45:43' '0a:74:47:e0:c9:03'
 '0a:7f:2a:8f:34:17' '0e:3f:d9:e6:6b:75' '12:2c:22:3f:8f:b7'
 '12:44:cd:3f:90:39' '12:de:67:be:0a:93' '16:8b:65:9b:f2:77'
 '1a:32:84:f9:d9:11' '1a:b5:24:b1:05:47' '1a:bf:56:94:b7:a2'
 '1a:ce:60:49:25:2c' '1a:d2:5e:86:d6:b1' '1e:46:fb:21:7d:ba'
 '1e:5a:47:93:77:3d' '1e:66:8b:37:9b:d5' '26:22:86:56:9e:59'
 '26:67:1b:cb:6e:47' '26:a5:06:6e:68:0a' '26:b4:4f:79:f8:41'
 '26:e7:03:03:d1:11' '2a:61:e1:68:04:45' '2a:6d:30:53:12:a1'
 '2a:ea:37:8d:de:39' '2e:29:60:92:9c:21' '36:3a:dc:ea:24:94'
 '36:6e:e9:ce:4c:a3' '36:f0:f2:07:c6:77' '3a:0e:4c:1c:c8:2f'
 '3a:75:f4:62:1a:b4' '3a:b8:6e:ef:4f:ab' '3e:b7:22:15:7f:a3'
 '3e:f7:f7:ce:75:72' '42:0d:76:f4:19:f7' '42:9a:ad:e0:e3:f6'
 '42:d4:39:5d:cd:0e' '46:82:86:c7:b1:72' '46:be:3e:e8:5b:02'
 '4a:f0:34:80:cc:3f' '52:4b:c5:3d:76:33' '52:56:0b:5e:25:69'
 '52:56:fe:e6:96:a9' '52:cc:c4:49:2f:5c' '56:54:b9:fa:a1:21'
 '5a:95:64:8f:b3:b6' '5a:fd:38:a4:04:c0' '5e:10:ec:1f:32:7d'
 '62:89:92:78:c8:41' '66:39:39:8f:44:ec' '66:4a:c1:26:f2:62'
 '6a:55:66:82:78:50' '6a:83:6f:53:72:19' '6a:a7:49:89:ea:df'
 '6e:49:36:21:e1:8e' '6e:bc:95:2c:43:b0' '72:23:46:5a:88:0c'
 '72:ad:7d:40:53:c8' '76:a8:e5:1f:24:37' '7a:30:c6:03:0f:db'
 '7a:63:2c:51:4e:f5' '7a:96:16:fd:3d:50' '7a:da:a6:69:9b:d8'
 '7e:60:65:97:43:ea' '7e:91:87:29:62:67' '7e:a4:4f:66:bb:92'
 '7e:d9:f2:d2:1d:ff' '82:12:1c:0f:65:e5' '82:b7:5a:db:5c:c4'
 '82:f2:e2:66:0d:fc' '86:73:12:87:0d:62' '86:e0:de:9e:32:ca'
 '8e:54:a3:6f:9c:c2' '8e:5f:d2:c9:03:c5' '92:2b:e4:8c:5d:15'
 '92:ae:50:01:10:33' '96:ef:9a:ab:c8:79' '96:fb:c3:d5:5f:dc'
 '9a:35:fa:55:52:62' '9a:ab:53:e5:6e:30' '9e:84:8b:61:7c:ef'
 '9e:9a:e2:14:c7:62' 'a6:82:13:11:40:dc' 'aa:d4:6e:ee:71:15'
 'aa:d5:ee:f4:ae:bf' 'ae:fd:1e:7c:e9:c8' 'b2:01:c5:7f:27:4b'
 'b2:ab:f5:f4:6a:ec' 'b6:0c:bf:df:a0:50' 'b6:1f:76:06:e8:16'
 'b6:f3:8b:98:98:da' 'ba:88:77:4b:7a:8c' 'ba:ae:31:2f:cf:0b'
 'be:05:40:56:af:35' 'be:43:b8:26:a5:9e' 'c2:1b:0a:42:59:50'
 'c6:59:24:98:5d:4b' 'c6:da:6a:b3:86:fc' 'c6:e0:92:6b:61:09'
 'ca:8f:ab:a3:01:61' 'ca:9a:c1:84:bf:6d' 'ca:a0:6b:1e:81:50'
 'ca:de:d2:be:ba:1a' 'ce:8a:f7:cc:bc:ba' 'd2:46:92:96:89:55'
 'd2:e8:4e:73:71:ab' 'd6:39:78:19:66:63' 'd6:bb:96:fb:eb:32'
 'd6:eb:d0:ef:5c:ec' 'da:3c:d0:c2:0c:21' 'da:41:df:d7:34:d7'
 'da:5f:73:c1:ec:43' 'da:b6:c3:fa:48:12' 'da:b8:41:50:18:6e'
 'da:d8:23:79:da:25' 'de:81:f9:b5:80:46' 'de:b6:f1:0c:e7:ff'
 'e2:05:e4:4f:fd:94' 'e2:65:c2:f0:63:60' 'e6:05:ff:97:a1:ef'
 'e6:60:55:7b:db:39' 'e6:77:15:b2:16:d0' 'ea:3b:5b:86:87:15'
 'ea:d0:b7:53:a8:66' 'ea:d6:ac:26:11:1c' 'ee:c4:e2:97:4c:21'
 'f2:5a:4c:89:78:f9' 'f2:92:ec:65:b1:21' 'f2:94:c1:f2:86:9c'
 'f2:de:ab:e4:79:c5' 'f6:02:4a:2a:55:64' 'f6:03:da:61:b9:c4'
 'f6:14:48:57:4e:c3' 'f6:61:e8:74:79:90' 'f6:90:cb:29:ed:1b'
 'f6:d0:02:25:77:3b' 'f6:f8:8d:83:3c:a3' 'fa:44:c9:e6:30:71'
 'fa:57:8f:59:f4:bb' 'fa:6e:0b:1c:09:ce' 'fa:74:83:ee:9e:7c'
 'fa:9e:cc:a2:23:6d' 'fe:0c:fb:68:17:02' 'fe:22:29:f4:b5:ac'
 'fe:29:02:07:42:26' 'fe:79:1d:49:3b:fb' 'fe:8b:00:75:88:22']
Encoded Labels: 0          17
1          97
2          35
3         115
4          51
         ...
953733     97
953734    115
953735     93
953736    112
953737    129
Name: S_MAC, Length: 914332, dtype: object
Unique Classes: ['02:47:6a:5a:03:6a' '02:74:55:c5:ea:d9' '06:1d:58:18:44:d2'
 '06:29:f9:52:5c:f4' '06:79:dd:3f:87:16' '0a:4d:2d:fb:69:52'
 '0a:73:ba:bb:45:43' '0a:74:47:e0:c9:03' '0a:7f:2a:8f:34:17'
 '12:2c:22:3f:8f:b7' '12:de:67:be:0a:93' '16:8b:65:9b:f2:77'
 '1a:32:84:f9:d9:11' '1a:ce:60:49:25:2c' '1a:d2:5e:86:d6:b1'
 '1e:46:fb:21:7d:ba' '26:67:1b:cb:6e:47' '26:a5:06:6e:68:0a'
 '26:b4:4f:79:f8:41' '26:e7:03:03:d1:11' '2a:3d:d0:f5:3e:1d'
 '2a:61:e1:68:04:45' '2a:ea:37:8d:de:39' '2e:29:60:92:9c:21'
 '36:3a:dc:ea:24:94' '36:6e:e9:ce:4c:a3' '3a:75:f4:62:1a:b4'
 '3a:b8:6e:ef:4f:ab' '3a:d4:c9:f6:b2:7e' '3e:b7:22:15:7f:a3'
 '3e:f7:f7:ce:75:72' '42:0d:76:f4:19:f7' '42:9a:ad:e0:e3:f6'
 '42:d4:39:5d:cd:0e' '46:be:3e:e8:5b:02' '4a:f0:34:80:cc:3f'
 '52:4b:c5:3d:76:33' '52:56:0b:5e:25:69' '52:56:fe:e6:96:a9'
 '56:54:b9:fa:a1:21' '5a:fd:38:a4:04:c0' '5e:10:ec:1f:32:7d'
 '62:89:92:78:c8:41' '62:96:19:42:3d:5f' '66:24:4d:0d:e1:00'
 '66:39:39:8f:44:ec' '66:4a:c1:26:f2:62' '66:7c:96:3f:9d:9e'
 '6a:55:66:82:78:50' '6a:83:6f:53:72:19' '6a:a7:49:89:ea:df'
 '6e:49:36:21:e1:8e' '6e:b7:66:25:a7:5e' '6e:bc:95:2c:43:b0'
 '72:23:46:5a:88:0c' '72:67:7a:d9:e2:fd' '72:ad:7d:40:53:c8'
 '76:19:4c:e0:28:a5' '7a:30:c6:03:0f:db' '7a:63:2c:51:4e:f5'
 '7a:da:a6:69:9b:d8' '7a:e3:0d:64:1b:7a' '7e:60:65:97:43:ea'
 '7e:91:87:29:62:67' '7e:a4:4f:66:bb:92' '82:12:1c:0f:65:e5'
 '82:b7:5a:db:5c:c4' '82:f2:e2:66:0d:fc' '86:73:12:87:0d:62'
 '86:e0:de:9e:32:ca' '8a:87:7d:38:4d:d2' '8e:5f:d2:c9:03:c5'
 '92:2b:e4:8c:5d:15' '96:fb:c3:d5:5f:dc' '9a:35:fa:55:52:62'
 '9a:ab:53:e5:6e:30' '9e:68:c7:15:ff:56' '9e:84:8b:61:7c:ef'
 '9e:9a:e2:14:c7:62' 'aa:d4:6e:ee:71:15' 'aa:d5:ee:f4:ae:bf'
 'ae:fd:1e:7c:e9:c8' 'b2:01:c5:7f:27:4b' 'b6:0c:bf:df:a0:50'
 'b6:1f:76:06:e8:16' 'ba:ae:31:2f:cf:0b' 'be:05:40:56:af:35'
 'be:43:b8:26:a5:9e' 'c6:59:24:98:5d:4b' 'c6:e0:92:6b:61:09'
 'ca:9a:c1:84:bf:6d' 'ca:de:d2:be:ba:1a' 'ce:8a:f7:cc:bc:ba'
 'd2:46:92:96:89:55' 'd2:84:86:c4:4d:e3' 'd2:c4:88:e3:23:70'
 'd2:e8:4e:73:71:ab' 'd6:a5:b5:2d:62:5b' 'd6:bb:96:fb:eb:32'
 'd6:eb:d0:ef:5c:ec' 'da:41:df:d7:34:d7' 'da:5f:73:c1:ec:43'
 'da:b6:c3:fa:48:12' 'da:d8:23:79:da:25' 'de:81:f9:b5:80:46'
 'de:b6:f1:0c:e7:ff' 'e2:05:e4:4f:fd:94' 'e2:65:c2:f0:63:60'
 'e6:05:ff:97:a1:ef' 'e6:60:55:7b:db:39' 'ea:d6:ac:26:11:1c'
 'ea:ff:a2:e9:10:ad' 'ee:c4:e2:97:4c:21' 'f2:5a:4c:89:78:f9'
 'f2:92:ec:65:b1:21' 'f6:02:4a:2a:55:64' 'f6:03:da:61:b9:c4'
 'f6:14:48:57:4e:c3' 'f6:61:e8:74:79:90' 'f6:90:cb:29:ed:1b'
 'f6:d0:02:25:77:3b' 'f6:f8:8d:83:3c:a3' 'fa:44:c9:e6:30:71'
 'fa:57:8f:59:f4:bb' 'fa:6e:0b:1c:09:ce' 'fa:9e:cc:a2:23:6d'
 'fe:0c:fb:68:17:02' 'fe:22:29:f4:b5:ac' 'fe:79:1d:49:3b:fb'
 'fe:8b:00:75:88:22']
Encoded Labels: 0         95
1         52
2         44
3         61
4         43
          ..
953733    52
953734    61
953735    43
953736    76
953737    43
Name: D_MAC, Length: 914332, dtype: object
Unique Classes: ['0.0.139.166' '0.0.141.91' '0.0.2.186' ... '99.99.79.225' '99.99.79.80'
 '99.99.96.135']
Encoded Labels: 0         357824
1         322577
2         207946
3           3333
4         105254
           ...
953733     39788
953734      3352
953735    285844
953736      3349
953737     35897
Name: SIP, Length: 914332, dtype: object
Unique Classes: ['10.0.0.1' '10.0.0.10' '10.0.0.11' '10.0.0.12' '10.0.0.13' '10.0.0.14'
 '10.0.0.15' '10.0.0.16' '10.0.0.17' '10.0.0.18' '10.0.0.19' '10.0.0.2'
 '10.0.0.20' '10.0.0.21' '10.0.0.22' '10.0.0.23' '10.0.0.3' '10.0.0.4'
 '10.0.0.5' '10.0.0.6' '10.0.0.7' '10.0.0.8' '10.0.0.9']
Encoded Labels: 0          3
1          0
2          4
3          7
4          2
          ..
953733     0
953734     7
953735     2
953736    16
953737     2
Name: DIP, Length: 914332, dtype: object
Unique Classes: ['attack' 'normal']
Encoded Labels: 0         0
1         0
2         0
3         0
4         0
         ..
953733    0
953734    0
953735    0
953736    0
953737    0
Name: label, Length: 914332, dtype: object
Unique Classes: ['Bhttp_flood.pcap' 'Bicmp_flood.pcap' 'Bmqtt_udp_flood.pcap'
 'Btcp_flood.pcap' 'Budp_flood.pcap' 'Hicmp_flood.pcap' 'Htcp_flood.pcap'
 'Hudp_flood.pcap' 'hmqtt_TcpSyn_flood.pcap' 'mqtt_publish_flood1.pcap'
 'normal']
Encoded Labels: 0         7
1         5
2         6
3         3
4         8
         ..
953733    5
953734    3
953735    8
953736    4
953737    8
Name: type, Length: 914332, dtype: object
Unique Classes: ['CD' 'IoT' 'NU']
Encoded Labels: 0         2
1         2
2         2
3         2
4         1
         ..
953733    2
953734    2
953735    1
953736    2
953737    1
Name: D_type, Length: 914332, dtype: object

In [22]:
EY

,S_MAC,D_MAC,FPT,LPT,SIT,STT,SIP,DIP,SPort,DPort,label,type,D_type
0,17,95,1.741113e+09,1.741113e+09,1.741113e+09,1.741113e+09,357824,3,6284,5001,0,7,2
1,97,52,1.741114e+09,1.741114e+09,1.741114e+09,1.741114e+09,322577,0,0,0,0,5,2
2,35,44,1.741112e+09,1.741112e+09,1.741112e+09,1.741112e+09,207946,4,29060,8008,0,6,2
3,115,61,1.741169e+09,1.741169e+09,1.741169e+09,1.741169e+09,3333,7,13213,12345,0,3,2
4,51,43,1.741118e+09,1.741118e+09,1.741118e+09,1.741118e+09,105254,2,15807,1883,0,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
953733,97,52,1.741114e+09,1.741114e+09,1.741114e+09,1.741114e+09,39788,0,0,0,0,5,2
953734,115,61,1.741169e+09,1.741169e+09,1.741169e+09,1.741169e+09,3352,7,14629,12345,0,3,2
953735,93,43,1.741118e+09,1.741118e+09,1.741118e+09,1.741118e+09,285844,2,12072,1883,0,8,1
953736,112,76,1.741167e+09,1.741167e+09,1.741167e+09,1.741167e+09,3349,16,16754,53,0,4,2
953737,129,43,1.741118e+09,1.741118e+09,1.741118e+09,1.741118e+09,35897,2,33670,1883,0,8,1

In [23]:
for i in Y:
    if Y[i].isnull().sum()>0:
        print(i)

In [24]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
X_train_scaled = scaler.fit_transform(X)

In [25]:

X_train_scaled = pd.DataFrame(X_train_scaled,columns = X.columns)
X_train_scaled

,FD,FAMin,FAMean,FAMax,FAStd,FIMean,FIMin,FIMax,FIStd,DSCP_C,...,PEntropy,FIPD_Var,BIPD_Var,TCPWS_Sum,TCPWS_Mean,TCPWS_Mode,HTTPRM_L,HTTPRM_UL,HTTP_SCL,HTTP_SCUL:
0,0.0,0.053732,0.000638,0.000638,0.0,0.500227,0.500227,0.500227,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
1,0.0,0.053732,0.000638,0.000638,0.0,0.500227,0.500227,0.500227,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
2,0.0,0.053732,0.000638,0.000638,0.0,0.500227,0.500227,0.500227,0.0,0.0,...,0.0,0.0,0.0,0.000287,0.011786,0.011786,0.0,0.0,0.0,0.0
3,0.0,0.053732,0.000638,0.000638,0.0,0.500227,0.500227,0.500227,0.0,0.0,...,0.0,0.0,0.0,0.002295,0.094291,0.094291,0.0,0.0,0.0,0.0
4,0.0,0.053732,0.000638,0.000638,0.0,0.500227,0.500227,0.500227,0.0,0.0,...,0.0,0.0,0.0,0.000287,0.011786,0.011786,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
914327,0.0,0.053732,0.000638,0.000638,0.0,0.500227,0.500227,0.500227,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
914328,0.0,0.053732,0.000638,0.000638,0.0,0.500227,0.500227,0.500227,0.0,0.0,...,0.0,0.0,0.0,0.002295,0.094291,0.094291,0.0,0.0,0.0,0.0
914329,0.0,0.053732,0.000638,0.000638,0.0,0.500227,0.500227,0.500227,0.0,0.0,...,0.0,0.0,0.0,0.000287,0.011786,0.011786,0.0,0.0,0.0,0.0
914330,0.0,0.053732,0.000638,0.000638,0.0,0.500227,0.500227,0.500227,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
914331,0.0,0.053732,0.000638,0.000638,0.0,0.500227,0.500227,0.500227,0.0,0.0,...,0.0,0.0,0.0,0.000287,0.011786,0.011786,0.0,0.0,0.0,0.0

In [26]:
# from sklearn.preprocessing import MinMaxScaler
# import numpy as np

# # Sample Training Data
# X_train = np.array([[10, 200],
#                     [20, 400],
#                     [30, 600],
#                     [40, 800]])  # Features: 2 columns

# # Initialize and fit the scaler on training data
# scaler = MinMaxScaler()
# X_train_scaled = scaler.fit_transform(X_train)

# # Save the trained scaler for future use
# import joblib
# joblib.dump(scaler, "scaler.pkl")

# print("Scaled Training Data:\n", X_train_scaled)

# # Load the saved scaler
# scaler = joblib.load("scaler.pkl")

# # Real-Time Test Data (New values that may not have the same min/max)
# X_test = np.array([[15, 300],
#                    [25, 500]])  

# # Transform using the SAME scaler (without fitting again)
# X_test_scaled = scaler.transform(X_test)

# print("Scaled Test Data:\n", X_test_scaled)

In [ ]:
# Attack Identification
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score


# Load the dataset

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_train_scaled.iloc[:,:],EY.iloc[:,-3].astype('int'), test_size=0.2, random_state=42)

# Create a random forest classifier
clf = RandomForestClassifier(random_state=42)
# kernels = ['linear', 'poly', 'rbf', 'sigmoid']
# clf = SVC(kernel='linear', C=1.0, random_state=42)


# Define a function for evaluating a set of features using cross-validation
def evaluate_features(clf,features,X_train,y_train,y_test):
    clf.fit(X_train.iloc[:,features], y_train)
    y_pred = clf.predict(X_test.iloc[:, features])
    return accuracy_score(y_test, y_pred)

# Perform wrapper feature selection
num_features = X_train.shape[1]
selected_features = []
best_accuracy = 0

for _ in range(num_features):
    best_feature = None
    for feature in range(num_features):
        if feature not in selected_features:
            current_features = selected_features + [feature]
            #print(current_features)
            accuracy = evaluate_features(clf,current_features,X_train,y_train,y_test)
            if accuracy > best_accuracy:
                best_accuracy = accuracy
                best_feature = feature
    if best_feature is not None:
        selected_features.append(best_feature)
        print(f"Selected feature {best_feature}, Accuracy: {best_accuracy:.5f}")

print("Selected features:", selected_features)

In [17]:
selected_features= [52, 35, 40, 59, 44, 6, 12]
X.iloc[:,selected_features]

          FEntropy  RTT  FIN_FC  TCPWS_Mean  RCount  FIMin  TBytes
0      -226.477332  0.0       0         0.0       0    0.0      42
1      -226.477332  0.0       0         0.0       0    0.0      42
2      -310.763925  0.0       0       512.0       0    0.0      54
3      -369.160171  0.0       0      4096.0       0    0.0      62
4      -310.763925  0.0       0       512.0       0    0.0      54
...            ...  ...     ...         ...     ...    ...     ...
953733 -226.477332  0.0       0         0.0       0    0.0      42
953734 -459.499549  0.0       0      4096.0       0    0.0      74
953735 -310.763925  0.0       0       512.0       0    0.0      54
953736 -459.499549  0.0       0         0.0       0    0.0      74
953737 -310.763925  0.0       0       512.0       0    0.0      54

[953738 rows x 7 columns]

In [27]:
# Attack Identification With Device Type
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score


# Load the dataset

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_train_scaled.iloc[:,:],EY.iloc[:,-2].astype('int'), test_size=0.2, random_state=42)
print(EY.columns[-2])
# Create a random forest classifier
clf = RandomForestClassifier(random_state=42)
# kernels = ['linear', 'poly', 'rbf', 'sigmoid']
# clf = SVC(kernel='linear', C=1.0, random_state=42)


# Define a function for evaluating a set of features using cross-validation
def evaluate_features(clf,features,X_train,y_train,y_test):
    clf.fit(X_train.iloc[:,features], y_train)
    y_pred = clf.predict(X_test.iloc[:, features])
    return accuracy_score(y_test, y_pred)

# Perform wrapper feature selection
num_features = X_train.shape[1]
selected_features = []
best_accuracy = 0

for _ in range(num_features):
    best_feature = None
    for feature in range(num_features):
        if feature not in selected_features:
            current_features = selected_features + [feature]
            #print(current_features)
            accuracy = evaluate_features(clf,current_features,X_train,y_train,y_test)
            if accuracy > best_accuracy:
                best_accuracy = accuracy
                best_feature = feature
    if best_feature is not None:
        selected_features.append(best_feature)
        print(f"Selected feature {best_feature}, Accuracy: {best_accuracy:.5f}")

print("Selected features:", selected_features)

label
Selected feature 52, Accuracy: 0.98564
Selected feature 35, Accuracy: 0.99641
Selected feature 65, Accuracy: 0.99942
Selected feature 58, Accuracy: 0.99985
Selected feature 40, Accuracy: 0.99994
Selected feature 22, Accuracy: 0.99996

KeyboardInterrupt:

In [15]:
selected_features=[52,35,65,58,40,22]
X_train_scaled.iloc[:,selected_features]

        FEntropy  RTT  D_type  TCPWS_Sum  FIN_FC  FlowStd
0       0.996710  0.0     1.0   0.000000     0.0      0.0
1       0.996710  0.0     1.0   0.000000     0.0      0.0
2       0.996205  0.0     1.0   0.000287     0.0      0.0
3       0.995854  0.0     1.0   0.002295     0.0      0.0
4       0.996205  0.0     0.5   0.000287     0.0      0.0
...          ...  ...     ...        ...     ...      ...
953733  0.996710  0.0     1.0   0.000000     0.0      0.0
953734  0.995312  0.0     1.0   0.002295     0.0      0.0
953735  0.996205  0.0     0.5   0.000287     0.0      0.0
953736  0.995312  0.0     1.0   0.000000     0.0      0.0
953737  0.996205  0.0     0.5   0.000287     0.0      0.0

[953738 rows x 6 columns]

In [ ]:
52,35,65,58,40,22

# Device Classification

In [18]:
# @title
selected4rmPreviousRun=[35,54,58,40,53,1,5,8,12,0,42,56]
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score


# Load the dataset

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_train_scaled.iloc[:,:],EY.iloc[:,-1].astype('int'), test_size=0.2, random_state=42)

# Create a random forest classifier
clf = RandomForestClassifier(random_state=42)
# kernels = ['linear', 'poly', 'rbf', 'sigmoid']
# clf = SVC(kernel='linear', C=1.0, random_state=42)


# Define a function for evaluating a set of features using cross-validation
def evaluate_features(clf,features,X_train,y_train,y_test):
    clf.fit(X_train.iloc[:,features], y_train)
    y_pred = clf.predict(X_test.iloc[:, features])
    return accuracy_score(y_test, y_pred)

# Perform wrapper feature selection
num_features = X_train.shape[1]
# selected_features = []
selected_features = selected4rmPreviousRun
best_accuracy = 0

for _ in range(num_features):
    best_feature = None
    for feature in range(num_features):
        if feature not in selected_features:
            current_features = selected_features + [feature]
            #print(current_features)
            accuracy = evaluate_features(clf,current_features,X_train,y_train,y_test)
            if accuracy > best_accuracy:
                best_accuracy = accuracy
                best_feature = feature
    if best_feature is not None:
        selected_features.append(best_feature)
        print(f"Selected feature {best_feature}, Accuracy: {best_accuracy:.5f}")

print("Selected features:", selected_features)

Selected feature 3, Accuracy: 0.84544
Selected feature 59, Accuracy: 0.84548
Selected feature 52, Accuracy: 0.84551
Selected feature 55, Accuracy: 0.84553
Selected features: [35, 54, 58, 40, 53, 1, 5, 8, 12, 0, 42, 56, 3, 59, 52, 55]

In [19]:
#selected4rmPreviousRun=[35,54,58,40,53,1,5,8,12,0,42,56,3,59,52,55]
X_train_scaled.iloc[:,selected_features]

,RTT,PL,TCPWS_Sum,FIN_FC,PIA_Var,FAMin,FIMean,FIStd,TBytes,FD,PSH_FC,FIPD_Var,FAMax,TCPWS_Mean,FEntropy,PEntropy
0,0.0,0.000000,0.000000,0.0,0.0,0.053732,0.500227,0.0,0.000000,0.0,0.0,0.0,0.000638,0.000000,0.996710,0.0
1,0.0,0.000000,0.000000,0.0,0.0,0.053732,0.500227,0.0,0.000000,0.0,0.0,0.0,0.000638,0.000000,0.996710,0.0
2,0.0,0.000000,0.000287,0.0,0.0,0.053732,0.500227,0.0,0.000002,0.0,0.0,0.0,0.000638,0.011786,0.996205,0.0
3,0.0,0.000000,0.002295,0.0,0.0,0.053732,0.500227,0.0,0.000004,0.0,0.0,0.0,0.000638,0.094291,0.995854,0.0
4,0.0,0.000000,0.000287,0.0,0.0,0.053732,0.500227,0.0,0.000002,0.0,0.0,0.0,0.000638,0.011786,0.996205,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
953733,0.0,0.000000,0.000000,0.0,0.0,0.053732,0.500227,0.0,0.000000,0.0,0.0,0.0,0.000638,0.000000,0.996710,0.0
953734,0.0,0.000000,0.002295,0.0,0.0,0.053732,0.500227,0.0,0.000007,0.0,0.0,0.0,0.000638,0.094291,0.995312,0.0
953735,0.0,0.000000,0.000287,0.0,0.0,0.053732,0.500227,0.0,0.000002,0.0,0.0,0.0,0.000638,0.011786,0.996205,0.0
953736,0.0,0.000004,0.000000,0.0,0.0,0.053732,0.500227,0.0,0.000007,0.0,0.0,0.0,0.000638,0.000000,0.995312,0.0
953737,0.0,0.000000,0.000287,0.0,0.0,0.053732,0.500227,0.0,0.000002,0.0,0.0,0.0,0.000638,0.011786,0.996205,0.0

In [28]:
#### important features ####

a=['FEntropy','RTT','FIN_FC','TCPWS_Mean','RCount','FIMin','TBytes'] #  Attack Classification Without Device Type, Acc% 99.943

b=['FEntropy','RTT','D_type','TCPWS_Sum','FIN_FC','FlowStd']  # Attack Classification Device Type, Acc% 99.996

c=['RTT','PL','TCPWS_Sum','FIN_FC','PIA_Var','FAMin','FIMean','FIStd','TBytes','FD','PSH_FC','FIPD_Var','FAMax','TCPWS_Mean','FEntropy','PEntropy'] # Device Classification Device Type, Acc% 84.553

In [29]:
union_list = list(set(a) | set(b) | set(c))
print(union_list)
print(len(union_list))

['TCPWS_Sum', 'FIMin', 'FD', 'FEntropy', 'D_type', 'FIMean', 'FlowStd', 'FAMin', 'RCount', 'PSH_FC', 'FIStd', 'RTT', 'FIN_FC', 'PL', 'TBytes', 'TCPWS_Mean', 'FAMax', 'PIA_Var', 'FIPD_Var', 'PEntropy']
20

In [ ]:
'FEntropy', 'RTT', 'D_type', 'TCPWS_Sum', 'FIN_FC', 'TBytes', 'PSH_FC', 'FJitter'

In [30]:
for i in union_list:
    print(i)

TCPWS_Sum
FIMin
FD
FEntropy
D_type
FIMean
FlowStd
FAMin
RCount
PSH_FC
FIStd
RTT
FIN_FC
PL
TBytes
TCPWS_Mean
FAMax
PIA_Var
FIPD_Var
PEntropy

# Here Extracting only require Flow

In [5]:
DT=['FAPS', 'TCPWS_Sum', 'Proto', 'BytesPS', 'FThroughput', 'FAMin', 'RCount', 'TCPWS_Mode', 'DSCP_C', 'TCPWS_Mean']

In [6]:
AD=['FEntropy', 'RTT', 'TCPWS_Sum', 'FIN_FC', 'TBytes', 'PSH_FC', 'FJitter']
#'D_type', from MACrecord

In [7]:
c=['S_MAC']

In [8]:
union_list = list(set(DT) | set(AD) | set(c))
print(union_list)
print(len(union_list))

['DSCP_C', 'TCPWS_Mode', 'FIN_FC', 'RCount', 'FAMin', 'S_MAC', 'TCPWS_Sum', 'FJitter', 'Proto', 'RTT', 'BytesPS', 'TBytes', 'FThroughput', 'TCPWS_Mean', 'FAPS', 'FEntropy', 'PSH_FC']
17